# Application-specific global configuration settings.
# These get loaded by config/initializers/app_config.rb and
# can be accessed via APP_CONFIG[:param]

# Example:
#
# superuser: mfischer
# per_page: 20
# array_of_arrays:
#   - [key, val]
#   - [key2, val2]
